apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: default
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: alpine:3.20
          command: ["sh", "-c"]
          args: ["echo hello from mk-orchestrator; sleep 3600"]
